Repository alkemyTech/OT151-SERVER, pull requests merged in 2022-03, with the labels that each got.

#18 feat/OT151-27: add migration and model for slide
  app/models/slide.rb
  db/migrate/20220224194045_create_slides.rb
  db/migrate/20220224201414_add_discarded_at_to_slides.rb
  db/schema.rb
  spec/factories/slides.rb
  spec/models/slide_spec.rb
Labels: enhancement

#20 feat/OT151-31: add middleware for ownership
  app/controllers/application_controller.rb
  app/controllers/concerns/authorized.rb
Labels: enhancement

#21 Setup Amazon S3 SDK for Active Storage in production
  .env.sample
  Gemfile
  Gemfile.lock
  config/environments/production.rb
  config/storage.yml
Labels: work in progress

#19 Added module for authentication
  app/controllers/application_controller.rb
  app/controllers/concerns/authenticable.rb
Labels: work in progress

#16 feat/OT151-23: add endpoint auth/login
  app/controllers/api/v1/auth_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/exception_handler.rb
  app/serializers/user_serializer.rb
  config/routes.rb
Labels: enhancement

#17 feat/OT151-39: add endpoint POST /categories
  app/controllers/api/v1/categories_controller.rb
  app/serializers/category_serializer.rb
  config/routes.rb
Labels: enhancement

#27 Feat/ot151 32 user update endpoint
  app/controllers/api/v1/users_controller.rb
  config/routes.rb
Labels: enhancement

#31 Ot151 41 endpoint eliminacion categorias
  app/controllers/api/v1/categories_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/controllers/concerns/authenticable.rb
  config/routes.rb
Labels: good first issue

#35 Fixed some code in category controller and in routes
  app/controllers/api/v1/categories_controller.rb
  config/routes.rb
Labels: bug

#39 feat/OT151-37: reusable image upload service
  app/models/application_record.rb
  app/models/concerns/handle_images.rb
Labels: enhancement

#29 Added welcome mailer
  app/controllers/api/v1/users_controller.rb
  app/mailers/user_welcome.rb
  app/views/user_welcome/send_user_welcome.html.erb
  app/views/user_welcome/send_user_welcome.text.erb
  config/environments/development.rb
Labels: enhancement

#41 feat/OT151-45: add activity migration and model
  app/models/activity.rb
  db/migrate/20220308160411_create_activities.rb
  db/migrate/20220308160425_add_discarded_at_to_activities.rb
  db/schema.rb
  spec/factories/activities.rb
  spec/models/activity_spec.rb
Labels: enhancement

#42 Added feature to return a token when a new user registers
  app/controllers/api/v1/users_controller.rb
  app/mailers/user_welcome.rb
  config/routes.rb
Labels: enhancement

#44 feat OT-151-34: add endpoint authenticated user
  app/controllers/api/v1/auth_controller.rb
  config/routes.rb
Labels: enhancement

#43 feat/OT151-48: add endpoint get /slides
  app/controllers/api/v1/slides_controller.rb
  app/serializers/slides_serializer.rb
  config/routes.rb
Labels: work in progress

#46 feat OT-151-38: add endpoint detail category
  app/controllers/api/v1/categories_controller.rb
  config/routes.rb
Labels: enhancement

#47 feat OT-151-42: add endpoint detail announcement
  app/controllers/api/v1/announcements_controller.rb
  app/serializers/announcement_serializer.rb
  config/routes.rb
Labels: enhancement

#48 feat OT-151-51: add endpoint create testimonial
  app/controllers/api/v1/testimonials_controller.rb
  config/routes.rb
Labels: enhancement

#49 FIxed conflicts in mailers from merge
  app/mailers/user_notifier_mailer.rb
  app/views/user_notifier_mailer/send_signup_email.html.erb
  config/environment.rb
  config/environments/production.rb
Labels: bug

#50 feat OT-151-54: Setup Kaminari and add pagination to testimonial
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/testimonials_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/paginable.rb
  app/models/testimonial.rb
  config/routes.rb
Labels: enhancement

#52 feat/OT151-53: add pagination to members
  app/controllers/api/v1/members_controller.rb
  app/controllers/concerns/paginable.rb
  app/models/member.rb
  app/serializers/members_serializer.rb
  config/routes.rb
Labels: enhancement

#53 feat/OT151-30: add endpoint delete users
  app/controllers/api/v1/users_controller.rb
  app/controllers/concerns/exception_handler.rb
  config/routes.rb
Labels: enhancement

#54 feat/OT151-25: add module authorized
  app/controllers/concerns/authorized.rb
Labels: wontfix

#56 Added endpoint for updating news
  app/controllers/api/v1/announcements_controller.rb
  app/controllers/api/v1/categories_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/serializers/announcement_serializer.rb
Labels: bug, enhancement

#51 feat OT-151-43: add endpoint create announcement
  app/controllers/api/v1/announcements_controller.rb
  app/models/announcement.rb
  app/serializers/announcement_serializer.rb
  db/migrate/20220310003916_add_column_to_announcements.rb
  db/schema.rb
  spec/factories/announcements.rb
  spec/models/announcement_spec.rb
Labels: work in progress

#64 feat/OT151-58: add slides doc
  app/serializers/slides_serializer.rb
  spec/integration/api/v1/slides/index_spec.rb
  spec/support/shared_contexts/integration_test.rb
  spec/swagger_helper.rb
Labels: enhancement

#66 Added documentation for members
  Gemfile
  Gemfile.lock
  spec/integration/api/v1/members/create_spec.rb
  spec/integration/api/v1/members/index_spec.rb
  spec/swagger_helper.rb
  swagger/v1/swagger.yaml
Labels: documentation

#70 Added tests for announcements endpoints
  config/routes.rb
  spec/factories/announcements.rb
  spec/factories/categories.rb
  spec/fixture/files/Rosario.jpg
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/api/v1/announcements/announcement_spec.rb
Labels: Test

#71 Added create endpoint for members
  app/controllers/api/v1/members_controller.rb
  app/serializers/members_serializer.rb
  config/routes.rb
  spec/factories/members.rb
Labels: enhancement

#73 Fixed factory for announcements
  spec/factories/announcements.rb
Labels: fix
